stages:
  - build-docker-image
  - checkstyle
  - static-code-analysis
  - test
  - build
  - build-rpm
  - deploy

variables:
  PROJECT_NAME_DIR: "zkPolicy"
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

cache:
  paths:
    - .m2/

default:
  before_script:
    - cd $PROJECT_NAME_DIR

build-docker:
  stage: build-docker-image
  when: manual
  only:
    refs:
      - ITHADOOP_767 # TODO: remove after testing
      - testing
      - qa
      - devops/koji-build
  script:
    - echo 'Build docker image...'
    - echo ${STAGE}
  variables:
    DOCKER_FILE: docker/DockerfileMVNBuilder
    TO: $CI_REGISTRY_IMAGE:mvn-builder
  tags:
    - docker-image-build

checkstyle:
  stage: checkstyle
  image: ${CI_REGISTRY_IMAGE}:mvn-builder
  script:
    - mvn clean checkstyle:checkstyle checkstyle:check
  artifacts:
    paths:
      - ${PROJECT_NAME_DIR}/target/checkstyle*
      - ${PROJECT_NAME_DIR}/target/site/checkstyle*
    expire_in: 1 week
  tags:
    - docker

pmd:
  stage: static-code-analysis
  image: ${CI_REGISTRY_IMAGE}:mvn-builder
  script:
    - mvn clean pmd:pmd pmd:check
  artifacts:
    paths:
      - ${PROJECT_NAME_DIR}/target/pmd*
      - ${PROJECT_NAME_DIR}/target/site/pmd*
    expire_in: 1 week
  tags:
    - docker

cpd:
  stage: static-code-analysis
  image: ${CI_REGISTRY_IMAGE}:mvn-builder
  script:
    - mvn clean pmd:cpd pmd:cpd-check
  artifacts:
    paths:
      - ${PROJECT_NAME_DIR}/target/cpd*
      - ${PROJECT_NAME_DIR}/target/site/cpd*
    expire_in: 1 week
  tags:
    - docker

spotbugs:
  stage: static-code-analysis
  image: ${CI_REGISTRY_IMAGE}:mvn-builder
  script:
    - mvn clean compile spotbugs:check -Dpmd.skip=true -Dcpd.skip=true -Dcheckstyle.skip=true
  artifacts:
    paths:
      - ${PROJECT_NAME_DIR}/target/spotbugs*
    expire_in: 1 week
  tags:
    - docker

test:
  stage: test
  image: ${CI_REGISTRY_IMAGE}:mvn-builder
  script:
    - mvn --quiet test -Dpmd.skip=true -Dcpd.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true
  artifacts:
    paths:
      - ${PROJECT_NAME_DIR}/target/surefire-reports
    expire_in: 1 week
  tags:
    - docker

build:
  stage: build
  image: ${CI_REGISTRY_IMAGE}:mvn-builder
  except:
    - qa
    - master
  script:
    - mvn --quiet package -DskipTests -Dpmd.skip=true -Dcpd.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true
  tags:
    - docker
  artifacts:
    paths:
      - target/
    expire_in: 8 hour

.koji_deps_template: &koji_deps
  before_script:
    - echo $KRB_PWD_RPM | kinit ${KRB_USER_RPM}@CERN.CH

build-rpm-testing:
  <<: *koji_deps
  stage: build-rpm
  image: ${CI_REGISTRY_IMAGE}:mvn-builder
  when: manual
  except:
    - qa
    - master
  script:
    - make add-testing
    - make kbuild
  dependencies:
    - build
  tags:
    - docker

tag-qa:
  <<: *koji_deps
  stage: deploy
  image: ${CI_REGISTRY_IMAGE}:mvn-builder
  when: manual
  only:
    - qa
  script:
    - make add-qa
    - make tag-qa
  allow_failure: false
  dependencies: []
  tags:
    - docker

tag-stable:
  <<: *koji_deps
  stage: deploy
  image: ${CI_REGISTRY_IMAGE}:mvn-builder
  when: manual
  only:
    - master
  script:
    - make add-stable
    - make tag-stable
  allow_failure: false
  dependencies: []
  tags:
    - docker