---
timeout: 2000
zkservers: "127.0.0.1:2183,127.0.0.1:2182,127.0.0.1:2181"

# colors for tree view output
# Available colors: RED, GREEN, BLACK, BLUE, YELLOW, MAGENTA, CYAN, WHITE
matchcolor: "GREEN"
mismatchcolor: "RED"
jaas: "/path/to/jaas.conf"
log4j: "/path/to/log4j.properties"