# Copyright © 2020, CERN
# This software is distributed under the terms of the MIT Licence,
# copied verbatim in the file 'LICENSE'. In applying this licence,
# CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

---
policies:
  - title: "HDFS/WebHDFS, No global read, r/w protected"
    query:
      name: "regexMatchPath"
      rootPath: "/hadoop-ha"
      args:
        - "/hadoop-ha"
    append: false
    acls:
      - "sasl:hdfs:cdrwa"
