# Copyright © 2020, CERN
# This software is distributed under the terms of the MIT Licence,
# copied verbatim in the file 'LICENSE'. In applying this licence,
# CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

---
policies:
  - title: "Hive/HCatalog, Open for global read, write protected"
    query:
      name: "regexMatchPath"
      rootPath: "/"
      args:
        - "/(?:hiveserver2|hivedelegation|llap-sasl/user-).*"
    append: false
    acls:
      - "world:anyone:r"
      - "sasl:hive:cdrwa"

  - title: "Hive/HCatalog, Completely open"
    query:
      name: "regexMatchPath"
      rootPath: "/"
      args:
        - "/(?:hive_zookeeper_namespace|llap-unsecure/user-).*"
    append: false
    acls:
      - "world:anyone:cdrwa"

  - title: "Hive/HCatalog, No global read, r/w protected"
    query:
      name: "regexMatchPath"
      rootPath: "/"
      args:
        - "/zkdtsm_[^/ ]+/ZKDTSMRoot/.*"
    append: false
    acls:
      - "sasl:hive:cdrwa"
