---
sections:
  generalInformation: true
  fourLetterWordCommands: true
  queryResults: true
  checkResults: true
  aclOverview: true

queries:
  # Fetch duplicate ACL entries
  - name: "duplicateACL"
    rootPath: "/hbase"

  # Fetch znodes not aligning with their parent ACL definition
  - name: "parentYesChildNo"
    rootPath: "/"

  # Fetch znodes that are open to any connected client
  - name: "noACL"
    rootPath: "/"

checks:
  # HBase
  - title: "Hbase Check, Open for global read, write protected"
    rootPath: "/hbase"
    pathPattern: "/hbase(?:|/master|/meta-region-server|/hbaseid|/table|/table/.*|/rs)"
    negate: false
    acls:
      - "world:anyone:r"
      - "sasl:hbase:cdrwa"

  - title: "Hbase Check, No global read, r/w protected"
    rootPath: "/hbase"
    pathPattern: "/hbase/(?:acl|rs/|namespace|backup-masters|online-snapshot|draining|replication|region-in-transition|splitWAL|table-lock|recovering-regions|running|tokenauth).*"
    negate: false
    acls:
      - "sasl:hbase:cdrwa"

  # HDFS
  - title: "HDFS/WebHDFS Check, No global read, r/w protected"
    rootPath: "/hadoop-ha"
    pathPattern: "/hadoop-ha"
    negate: false
    acls:
      - "sasl:hdfs:cdrwa"

  # Hive
  - title: "Hive/HCatalog Check, Open for global read, write protected"
    rootPath: "/"
    pathPattern: "/(?:hiveserver2|hivedelegation|llap-sasl/user-).*"
    negate: false
    acls:
      - "world:anyone:r"
      - "sasl:hive:cdrwa"

  - title: "Hive/HCatalog Check, Completely open"
    rootPath: "/"
    pathPattern: "/(?:hive_zookeeper_namespace|llap-unsecure/user-).*"
    negate: false
    acls:
      - "world:anyone:cdrwa"

  - title: "Hive/HCatalog Check, No global read, r/w protected"
    rootPath: "/"
    pathPattern: "/zkdtsm_[^/ ]+/ZKDTSMRoot/.*"
    negate: false
    acls:
      - "sasl:hive:cdrwa"

  # Kafka
  - title: "Kafka Check, Open for global read, write protected"
    rootPath: "/"
    pathPattern: "/(?:controller|isr_change_notification).*"
    negate: false
    acls:
      - "world:anyone:r"
      - "sasl:kafka:cdrwa"

  - title: "Kafka Check, Completely open"
    rootPath: "/"
    pathPattern: "/(?:brokers|admin|controller_epoch|consumers|config).*"
    negate: false
    acls:
      - "world:anyone:cdrwa"

  - title: "Kafka Check, No global read, r/w protected"
    rootPath: "/"
    pathPattern: "/kafka-acl.*"
    negate: false
    acls:
      - "sasl:kafka:cdrwa"

  - title: "Ooozie Check, No global read, r/w protected"
    rootPath: "/oozie"
    pathPattern: "/oozie.*"
    negate: false
    acls:
      - "sasl:oozie:cdrwa"

  - title: "YARN Check, Open for global read, write protected"
    rootPath: "/"
    pathPattern: "/(?:yarn-leader-election|rmstore)"
    negate: false
    acls:
      - "world:anyone:r"
      - "sasl:yarn:cdrwa"
