name: Package

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # RPM packaging
      - name: Build RPM artifacts
        uses: ./.github/actions/buildrpm
        id: buildrpm
        with:
          rootdir: "./"

      - name: Upload RPM artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/_temp/_github_home/${{ steps.buildrpm.outputs.rpm_path }}/*/*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Upload SRPM artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/_temp/_github_home/${{ steps.buildrpm.outputs.source_rpm_path }}/*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true