name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          directory: ./zkPolicy
          maven_goals_phases: clean deploy
          maven_args: -Pdeploy -DskipTests -Dcheckstyle.skip -Dpmd.skip -Dcpd.skip -Dspotbugs.skip
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_CENTRAL_TOKEN }}